PREFIX fx:   <http://sparql.xyz/facade-x/ns/>
PREFIX xyz:  <http://sparql.xyz/facade-x/data/>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#>


SELECT ?subject ?theRange WHERE {
    ?subject rdfs:range ?rangeSource .
    
    OPTIONAL {
        FILTER (isBlank(?rangeSource)) .
        BIND("isBlank" AS ?isBlank) .
        ?subject rdfs:range/(owl:equivalentClass|owl:intersectionOf|owl:unionOf|owl:oneOf) [ (rdf:first|(rdf:rest/rdf:first)+)* ?range ]
        FILTER(isIRI(?range))
    }
    
    BIND(IF(!BOUND(?range), ?rangeSource, ?range) AS ?theRange)
}