PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX odrl: <http://www.w3.org/ns/odrl/2/>
PREFIX fx:   <http://sparql.xyz/facade-x/ns/>
PREFIX xyz:  <http://sparql.xyz/facade-x/data/>
PREFIX dct:  <http://purl.org/dc/terms/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT ?action ?label ?description ?note
WHERE {
 SERVICE <x-sparql-anything:> {
 	fx:properties fx:location "https://www.w3.org/ns/odrl/2/ODRL22.ttl" ; fx:media-type "text/turtle" .
	
	?action a odrl:Action .
	optional { ?action rdfs:label ?label } .
	optional { ?action skos:description ?description } .
	optional { ?action skos:note ?note }
	.
 }
}